### ISSUE TITLE
[Bug] Calendar can’t be accessed

### ISSUE THREAD

**Issue by DavidCh0ng** [AjayShanker-geek/owadio#13]
# **🐞 Bug Report**

## **Describe the bug**

Calendar can’t be accessed. It keeps spinning
*

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* Device: 
* OS: 

---

### **Additional context**

*

**Comment by AjayShanker-geek** [comment]
```
Error: ICalendarFormatException: The body is missing the property PRODID
```

Issue has been fixed, push for release soon.

**Comment by DavidCh0ng** [comment]
Hi,

It seems the issue is still persisting. Any update on this? Thanks!
